### ISSUE TITLE
Need to update two REFCASES

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CESM#110]
### Summary of Issue:

nanr noticed that B1850 points to the wrong REFCASE

> I set up the experiment database for the standard B1850 case, setting:
> RUN_REFCASE = b.e21.B1850.f09_g17.CMIP6-piControl.001, 
> 
> but my case is coming out of the box with this as my refcase: RUN_REFCASE=b.e20.B1850.f09_g17.pi_control.all.299_merge_v2

Similarly the BW1850 compset is pointing to an older REFCASE as well. All of the other compsets point to b.e21 REFCASES

### Expected behavior and actual behavior:

REFCASE should be b.e21.B1850.f09_g17.CMIP6-piControl.001
but is: b.e20.B1850.f09_g17.pi_control.all.299_merge_v2

### Steps to reproduce the problem. Include externals description file(s) and link to public repository):

```
SMS_Ln1.f09_g17.B1850.cheyenne_intel.allactive-defaultio> ./xmlquery RUN_REFCASE,RUN_REFDATE         
Results in group run_begin_stop_restart
	RUN_REFCASE: b.e20.B1850.f09_g17.pi_control.all.299_merge_v3
	RUN_REFDATE: 0134-01-01
```

And for BWHIST:

```
scripts/SMS_Ln1.f09_g17.BW1850.cheyenne_intel.allactive-defaultio.20190322_143108_50jbax> ./xmlquery RUN_REFCASE,RUN_REFDATE        
Results in group run_begin_stop_restart
	RUN_REFCASE: b.e20.B1850.f09_g17.pi_control.all.299_merge_v3waccm
	RUN_REFDATE: 0134-01-01
### What is the changeset ID of the code, and the machine you are using: cesm2.1.1-exp13
```

**Comment by billsacks** [comment]
Wait, are you sure that this is supposed to change? My understanding is that the refcase for B1850 is supposed to mimic how the B1850 cmip6 deck run was set up. But you're suggesting setting this up so that a new B1850 run points to `b.e21.B1850.f09_g17.CMIP6-piControl.001`. Isn't that the B1850 cmip6 deck run itself? If so, it seems that this can't be how the B1850 cmip6 run was set up, because it can't have been started from itself (that would be circular).

This should be checked with others before you make any changes.

**Comment by ekluzek** [comment]
Yep, I'll leave this for next week to get confirmation on.

**Comment by billsacks** [comment]
@ekluzek should we close this?

**Comment by ekluzek** [comment]
This is old enough that I think it's likely addressed, and there are several commits that reference it that have come in. When I look at the config_component.xml file it looks like it's been addressed as well. So I'm closing although I confess I'm not 100% sure that's right.
